### ISSUE TITLE
Feature - Create operator that takes a function.

### ISSUE THREAD

**Issue by MonsieurMan** [funkia/list#11]
The idea would be to have an operator that takes a function and a count to generate a new list.  

> At first, I thought that was what repeat was doing.

**Example**
```typescript
const generateDot = () => {
  const x = Math.random() * this.width;
  const y = Math.random() * this.height;
  return { x, y };
}

const dots = generate(generateDot, 50); // I couldn't find a name for the operator.
```

**Comment by paldepind** [comment]
Hello @MonsieurMan. Thank you for the suggestion 😄 

Here is one way you could do it with the current API.

```js
const dots = L.map(generateDot, L.range(0, 50));
```

But, what you're describing sounds a lot like the Ramda function called [times](http://ramdajs.com/docs/#times). With that function you'd do:

```js
const dots = L.times(generateDot, 50);
```

The function is also passed the current index but obviously, it doesn't have to use it.

Am I correct that your `generate` is the same as Ramda's `times`? If so then I think we should add it with that name 😄

**Comment by MonsieurMan** [comment]
Yes, that's exactly it !  

As for the name I don't know if you want to keep the exact same API as ramda, because I find `repeatFunc` to be more readable and consistent with `repeat`.

By the way I just wrote a first implementation like so:  
```typescript
export function repeatFunc<A>(func: () => A, times: number): List<A> {
  let l = empty();
  while(--times >= 0) {
    l = append(func(), l);
  }
  return l;
}
```

I'm just not happy about the unit test I wrote which is quite dirty.

Would you like me to PR ? I'd like to contribute to the project, it seems fun and I think we maybe going to adopt it at my company.

**Comment by paldepind** [comment]
I think I'd prefer to keep the same name as Ramda uses. I see your point with regards to `repeatFunc`. But I also think the name "times" is ok. `times` calls a given function a given number of _times_.

> Would you like me to PR ? I'd like to contribute to the project, it seems fun and I think we maybe going to adopt it at my company.

I'd love a PR ❤️ Your implementation looks good! I think it should pass the current index like Ramda does. Passing the index certainly doesn't hurt. And if the type for `func` is `(index: number) => A` then it's still fine to give a function with no arguments.

In the documentation I think it would be nice to have a simple example like this one:


```js
const l = times(n => n * n, 4); //=> list(0, 1, 4, 9)
```

And then also the example you gave to show that `times` is useful to create a list with data generated by an impure function.

```js
const dots = times(() => {
  const x = Math.random() * width;
  const y = Math.random() * height;
  return { x, y };
}, 50);
```

Having good "realistic" examples like that is something that I think the documentation is currently lacking.

> I'm just not happy about the unit test I wrote which is quite dirty.

You could do something like this maybe?

```js
const l = times(n => n * n, 4);
assert.isTrue(equals(l, list(0, 1, 4, 9)));
```

Also, be aware that when you add a new function you also have to add it in the [ramda file](https://github.com/funkia/list/blob/master/src/ramda.ts). Otherwise the tests will complain 😅

**Comment by MonsieurMan** [comment]
Here it is ! :smile:
